---
- hosts: docker
  tasks:
    - name: start container
      docker_container:
        name: "{{name}}"
        hostname: "{{name}}"
        image: oraclelinux:6.8
        state: started
        tty: yes

    - name: add container to inventory
      add_host:
        name: "{{name}}"
        ansible_host: "{{name}}"
        ansible_user: root
        ansible_connection: docker
        groups: containers
      changed_when: false
  vars:
      name: ubuntu


- hosts: containers
  tasks:
    - name: show local vars
      debug: msg={{ansible_default_ipv4.address}}
