---
- hosts: all
  tasks:
    - name: application service
      docker:
        name: nginx
        image: kitematic/hello-world-nginx
        state: started
        ports:
          - 8000:80
        expose:
          - 80
