---
- hosts: docker
  tasks:
    - name: start nginx in docker
      docker_container:
        name: nginx
        image: kitematic/hello-world-nginx
        state: started
        ports:
          - 8000:80
        expose:
          - 80
      tags: [always]

    - name: add container to inventory
      add_host:
        name: nginx
        ansible_connection: docker
      changed_when: false
      tags: [always]

    - name: inside docker
      delegate_to: nginx
      raw: hostname
      tags:
        - hostname

    - name: inside docker 2
      delegate_to: nginx
      raw: uname -a
      tags:
        - uname
