---
- hosts: docker
  connection: local
  gather_facts: no
  tasks:
    - name: application service
      docker_container:
        name: test1
        image: oraclelinux:6.8
        state: started
        tty: yes
        purge_networks: yes
        networks:
          - net1

- hosts: guest
  tasks:
    - name: inside docker
      shell: hostname
