---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: get file from minio
      s3:
        aws_access_key: KEQCNL9CNNDG5QU5T99C
        aws_secret_key: 5C6xmOFzFtjpIsEdFuhR/gV9Rvcs8brILJAjsx4l
        s3_url: fakes3://127.0.0.1:9000
        bucket: files
        mode: get
        object: "/{{ file_name }}"
        dest: "{{ dest | expanduser }}/{{ file_name }}"
  vars:
    file_name: mpv-media-player.pdf
    dest: ~/Downloads/tmp
