---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: application service
      debug: msg="{{item[0]}}"
      with_items: "{{users}}"
  vars:
      users:
        alice:
          - par1
          - par2
        bob:
          - par3
          - par4
